### ISSUE TITLE
finalize the data

### ISSUE THREAD

**Issue by joeycozza** [joeycozza/gobrisket#5]
Need to input some weight_post_cook that is located on the yellow paper at work into the initial data.

**Comment by joeycozza** [comment]
also input the beef rub name.
Also ask jimmy if we should estimate the weight_post_cook for the Chriskets.

**Comment by JimmyCozza** [comment]
@joeycozza I estimated them in the order form log "accounting" tab.  The 2 biggest ones are accurate.  The other 2 are estimates.  Check them and see if you think it's close or not.

**Comment by joeycozza** [comment]
Alright. I'll use the 2 larger data points, and I won't use the smaller estimates.

**Comment by joeycozza** [comment]
Also ask Brandon/Dan/Blake for specific notes about their briskets

**Comment by joeycozza** [comment]
Only thing left to do is ask Blake for specific notes about his Chriskets
